### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by maelle**
just have R CMD check pass before I do anything else

### CODE REVIEW

**Comment by maelle** [comment]
oh and I added an Rproj :-)

**Comment by maelle** [comment]
the only failing test is of cran_releases(), but I should remove that function in another PR, right?

**Comment by gaborcsardi** [comment]
> the only failing test is of cran_releases(), but I should remove that function in another PR, right?

Right. Feel free to merge.

**Comment by maelle** [comment]
I can't! I don't have any rights on this repo :wink:

**Comment by gaborcsardi** [comment]
Oh, wait, I'll transfer it.

**Comment by gaborcsardi** [comment]
Transfered.

**Pull request merged**
